spacetx/slicedimage

- slicedimage/_tile.py
> [easy] Rename source_fh_callable to source_fh_contextmanager

- slicedimage/io.py
Here I've passed an incorrect folder to `starfish.io.Stack.read()`
The error is generated by `slicedimage`, so it's not as clear as it could be what's gone wrong to a user who is operating on a local filesystem. 
```python
s2 = Stack()
s2.read(os.path.expanduser('~/google_drive/starfish/data/ISS/experiment.json'))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-49944e7f0b3b> in <module>()
1 # get ISS data, see how that works
2 s2 = Stack()
----> 3 s2.read(os.path.expanduser('~/google_drive/starfish/data/ISS/experiment.json'))
~/projects/spacetx/starfish/starfish/io.py in read(self, in_json_path_or_url)
33 
34     def read(self, in_json_path_or_url):
---> 35 …
```
> improve error message

- setup.py
Once #22 lands, I'd like to bump the version and release a new pip pkg.
> [easy] bump version

- slicedimage/backends/_caching.py
If someone evicts our cache entry between the time we check the cache and the time we read the cache, we get a KeyError.  See https://travis-ci.org/spacetx/starfish/builds/417492246 for an example of this happening.
Now we try to return the cache entry, and if that fails, we try to fetch the data.  When we fetch the data, we return it directly from the buffer instead of the cache to prevent the race condition from happening again.
> Make cache concurrency safe.

- slicedimage/cli/checksum.py
The job of tile writing is delegated to two components: a opener, which returns a context manager that acts like a file, and a writer, which takes that file-like object and writes the data to it.
The checksum cli command works by creating a non-operational context manager, paired with a writer that does nothing.  Unfortunately, to calculate the checksum, we need to actually write to the file.
This fix changes the context manager to have a write method that does nothing, and a writer that writes the original content of the file[1].  This way, we don't write the tile files.
[1] If a tile writer is not provided, then by default, it writes the tile data as a numpy array.
> Fix the checksum calculation in the cli command.

- slicedimage/backends/_caching.py
Don't write into the cache if the checksum does not match.
Depends on #36 in order to pass tests.
> Protect the cache against corrupted data.

- slicedimage/backends/_caching.py
This will allow us to avoid the corrupt cache entries due to manifests with bogus checksums.  This should land after #37 so we won't introduce new corrupt cache entries.
> Version the cache key

- slicedimage/_formats.py
- tests/io/v0_0_0/test_write.py
> [easy] import numpy as np

- setup.py
Once #51 lands, release a new version.
> bump to 0.0.3

- setup.py
> Exclude tests from installed packages.

- slicedimage/io.py
Instead of replicating write calls to multiple file handles, buffer the output and replay the data to the hash calculation and the actual file write.
This is necessary to support file formats that require seeking.
> Simplify tile writing

- slicedimage/backends/__init__.py
- slicedimage/backends/_caching.py
- slicedimage/io.py
- tests/io/v0_0_0/test_write.py
> Allow setting of size limit and directory

- slicedimage/io.py
Adds a `parse_collection` method that binds the parse_method, baseurl, and backend_config.  That allows for a method that simply accepts the name + the relative path or url (as a tuple).
This method is mapped over a threadpool to yield an iterable of name, partition tuples.  In the main thread, we add the partitions to the collection and return it.
> Parse collection documents in parallel.

- Makefile
- requirements-dev.txt
Gets rid of some of the makefile cruft.
> Switch to pytest

- slicedimage/__init__.py
- slicedimage/io.py
- tests/io_/test_versions.py
1. Create a list of all the file versions ever.
2. Properly export the v0_1_0 symbol.
> Create a list of file versions.

- slicedimage/io.py
It was not meant to be public.
> [easy] hide the parse_collection method.

- setup.py
Will land this after #88, #94, and #95.
> bump to 3.1.0

- slicedimage/backends/_http.py
- tests/io_/v0_1_0/test_http_backend.py
In the HTTP backend, we create a urllib3's retry policy and attach it to a python-requests session.
We test this by monkeypatching the code to retry on 404 errors (which we normally do not).  We attempt to fetch a file that's not present, but start a thread that creates the file after a short delay.  It should initially not find the file, and then eventually succeed.
Fixes https://github.com/spacetx/starfish/issues/1277
> Add retry for HTTP failures and network connectivity issues

- requirements.txt
- slicedimage/backends/__init__.py
- slicedimage/backends/_s3.py
- slicedimage/io.py
- tests/io_/v0_1_0/test_s3_backend.py
This is in support of https://github.com/spacetx/starfish/issues/1307
Test plan: Adds a test that retrieves a file from one of the starfish-spacetx buckets.
> Add a s3 backend to slicedimage

- Makefile
- tests/io_/v0_0_0/test_missing_shape.py
- tests/io_/v0_0_0/test_write.py
- tests/io_/v0_1_0/test_missing_shape.py
- tests/io_/v0_1_0/test_write.py
This brings the code style to match the rest of spacetx code.  Remove the extra ignored warning.
Depends on #103
> Fix W504 warnings

- Makefile
- requirements-dev.txt
- slicedimage/__init__.py
- slicedimage/_formats.py
- slicedimage/backends/__init__.py
- slicedimage/backends/_caching.py
> add mypy support

- slicedimage/url/path.py
- slicedimage/url/resolve.py
This will be used to build datasets where tiles are at arbitrary URLs.
Test plan: Wrote some basic tests.
> Utility method to calculate the relative url from another url.

- slicedimage/io/__init__.py
- slicedimage/url/test/test_calculate_relative_url.py
- slicedimage/urlpath.py
These should have been in #103, but I missed them. :(
> Add missing files

- slicedimage/_tileset.py
- slicedimage/backends/_base.py
- slicedimage/cli/_base.py
- slicedimage/io/_base.py
> [easy] Add abstractmethod decorators to abstract methods

- .travis.yml
Depends on #115, #116, #117, #118, #119, #120, #121
> Enable travis on Windows

- slicedimage/io/_base.py
- slicedimage/url/path.py
- slicedimage/url/resolve.py
This is the same issue as #112, so I added a general method to do this conversion.
> Refactor file-url-to-path
