- slicedimage/cli/checksum.py
- slicedimage/io.py
It's useful to be able to resolve a URL or an absolute/relative path.  Use case: `Stack().read("http://xyz")` or `Stack().read("ISS/fov_001/experiment.json")`
Improve the documentation for `resolve_url`.
> Extract out path resolution from checksum cli command.

- slicedimage/io.py
- tests/io/v0_0_0/test_write.py
1. toc_path_generator should take one argument (path of the previous level TOC).
2. Add the sub-tocs to the output.
3. Add test to cover these code paths.
> Fix multilevel TOC write

- README.rst
- slicedimage/_tocpartition.py
- slicedimage/io.py
- tests/io/v0_0_0/test_reader.py
- tests/io/v0_0_0/test_write.py
- tests/io/v0_0_0/tocpartition_l1.json
- tests/io/v0_0_0/tocpartition_l2.json
Each TOC in a multilevel TOC should have a logical name.  This allows us to find a specific TOC (a.k.a. FOV in starfish parlance) by name.
Depends on #7
> Multilevel TOCs should have names.

- slicedimage/_tileset.py
https://github.com/spacetx/slicedimage/pull/13 provides the wrong default value.  It should be None if it's not present, or a tuple if it's present.
> fix tile_shape handling if it's not provided.

- slicedimage/io.py
The list of extensions we know does not include the '.'.  This allows us to match that list.
> Strip the extension of the '.'

- tests/io/v0_0_0/test_http_backend.py
Add a test that creates a TIFF-based tileset, and retrieve it over a locally running HTTP server.
> Test that remote retrieval of TIFF-based tilesets work.

- slicedimage/io.py
- tests/io/test_resolve_url.py
url = "abc/def", baseurl = "https://github.com/" should resolve to name=def, baseurl = "https://github.com/abc", but it wasn't previously.
Added test cases for all the resolve_* methods.
Fixes #25
> Fix resolution of relative paths with a path component.

- slicedimage/_formats.py
- slicedimage/backends/_base.py
- slicedimage/backends/_caching.py
- slicedimage/backends/_disk.py
- slicedimage/backends/_http.py
- slicedimage/io.py
- tests/io/v0_0_0/test_http_backend.py
If true, this forces the backend to return a seekable handle.  The short version is that this means we do not use streaming, and we have to buffer the contents.  This increases our memory consumption by ~2x, but it should be survivable.
Add a test for loading numpy arrays over http.  Fails without the changes in slicedimage/{backends/*,io.py}, but passes with the changes.  Yay!
Depends on #20
> Add a seekable argument to the read_file_handle_callable methods.

- tests/io/v0_0_0/test_caching_backend.py
It should be the checksum of the file, not the data.
> Fix calculation of test data's checksum

- tests/io/test_resolve_url.py
- tests/io/v0_0_0/test_caching_backend.py
- tests/io/v0_0_0/test_http_backend.py
- tests/io/v0_0_0/test_reader.py
- tests/io/v0_0_0/test_write.py
Import hack is only necessary if one does not run `pip install -e .`, and that's a logical thing to do for libraries.
Also cleaned up some import statements.
Fixes #31
> Remove import hack.

- Makefile
`make` without a target picks the first target.  This should be `test`, and not `lint`
> [easy] Reorder the targets

- slicedimage/_tile.py
- slicedimage/backends/_base.py
- slicedimage/backends/_caching.py
- slicedimage/backends/_disk.py
- slicedimage/backends/_http.py
- slicedimage/cli/checksum.py
- slicedimage/io.py
Context managers checks the feature list we need for this interface: an object that promises a file-like read handle, but doesn't do the work until it's invoked.  Previously, we did this by returning a method that, when called, would return the file-like handle.  The downside is that we can't execute any cleanup logic.  With context managers, we can require that a block of code is executed once the file-like read handle is no longer necessary.
Currently, this is just used to close the file handle (by invoking the wrapped context managers's __exit__method), but the next step is to use this cleanup block to verify that the data read matched the checksums.
> Convert read_file_handle{,_callable} to read_contextmanager

- slicedimage/io.py
- tests/io/v0_0_0/test_http_backend.py
The defaults are all set to True, but this allows us to test the disk and http backends properly.
> Add plumbing to disable caching.

- slicedimage/_formats.py
- slicedimage/backends/_base.py
- slicedimage/backends/_caching.py
- slicedimage/backends/_disk.py
- slicedimage/backends/_http.py
- slicedimage/io.py
We always want seekable=True.  Even though PIL claims to support streaming TIFF decoding, it actually reads into a [BytesIO object and decodes from that](https://pillow.readthedocs.io/en/3.0.x/releasenotes/2.8.0.html).  Therefore, there is no advantage to maintaining a streaming API.
> Remove the seekable parameter.

- slicedimage/backends/__init__.py
- slicedimage/backends/_base.py
- slicedimage/backends/_caching.py
- slicedimage/backends/_disk.py
- slicedimage/backends/_http.py
- tests/io/v0_0_0/test_disk_backend.py
- tests/io/v0_0_0/test_http_backend.py
1. Added a `verify_checksum` method to the _base class.  It takes a handle, reads the data by chunk, and verifies the checksum.
2. Remove checksum validation from CacheBackend if we are populating the cache (assumption: the backend supplying the data should have validated the checksum.  However, we will now validate the data coming from the cache.
3. Ported the tests from #42.
> Add checksum verification to disk and http backends

- requirements.txt
- setup.py
For platforms that do not need enum34, conda packages
are not being built. As a part of getting starfish
built in bioconda, the enum34 dependency has been
disabled as an install dependency. pkg_resources'
load_entry_point however still assumes that enum34
is required due to setup.py and fails with:
```
pkg_resources.DistributionNotFound:
The 'enum34' distribution was not found
and is required by slicedimage
```
see:
- https://github.com/spacetx/starfish/issues/44
- https://github.com/bioconda/bioconda-recipes/pull/10637
> enum34: remove dependency on py34+

- slicedimage/io.py
- tests/io/v0_0_0/test_write.py
The checksums attached to the tiles are the checksums at the time the tile is loaded.  It should not be used to write the tiles.
This should address the issue in this [comment](https://github.com/spacetx/starfish/issues/458#issuecomment-415213814)
Depends on #50 
Test plan: Add a test that writes a TIFF tileset, loads it back up, writes as a NUMPY tileset, and load that back up.  Without the change in slicedimage/io.py, it writes the checksum for the TIFF file and the load (and the test) fails.  With the change, the test passes.
> Always calculate checksums when writing tiles.

- setup.py
- slicedimage/backends/_caching.py
- tests/io/v0_0_0/test_caching_backend.py
Somehow, I made a mistake in merging my changes, and did not pass the checksum to the backend (I swear I ran into the same problem last time and fixed it already, but clearly it's not in the repo...).  To prevent repeating the mistake, I wrote a test to cover this case.
Bump the cache version to invalidate the caches with this bug.
Test plan: stashed the change to slicedimage/backends/_caching.py → test fails.
> Prevent cache pollution

- setup.py
- slicedimage/backends/_caching.py
Each instance holds open file handles, and each time we instantiate a backend, we rack up open file handles until we run out of them.
Test plan: Use this to successfully load the osmFISH data set in a python notebook.
> Reuse python diskcache instances

- slicedimage/_formats.py
- slicedimage/_tile.py
- slicedimage/io.py
- tests/io/v0_0_0/test_write.py
1. Adds a writer func to the ImageFormat class.
2. Instead of the tile writer callback dictating the file format, it now receives the requested file format and attempts to write it in that format.
3. Adds a test that writes out a TIFF set and reads it back.
Fixes https://github.com/spacetx/slicedimage/issues/2
> Allow writing to non-numpy file formats.

- setup.py
- slicedimage/_tile.py
- slicedimage/_typeformatting.py
- tests/test_tile_coordinates.py
If the input is a range, keep it a range.  If it's a scalar value, transform it into (scalar value, scalar value).
Bump version to 0.1.0 to reflect that the API has changed.
Test plan: wrote tests detailing the various possible inputs.
> Always represent coordinates internally as a range.

- slicedimage/_tile.py
- slicedimage/io.py
Currently, if we want to use a future to provide image data for a tile, we have to wrap it in a BytesIO object and then use `set_source_fh_contextmanager`.  This removes the necessity for wrapping.
We need to use this interface to load data into memory more selectively, rather than all at once.
Test plan: `make -j test`
> Add a numpy-array-future data source for tiles.

- slicedimage/backends/_base.py
- tests/io/v0_0_0/test_caching_backend.py
- tests/io/v0_0_0/test_disk_backend.py
- tests/io/v0_0_0/test_http_backend.py
1. Add documentation.
2. Add expectation that it should be possible to invoke the context manager multiple times.
3. Add tests for reentrancy.
Depends on #68, #70
> Explicitly spell out the contract for read_contextmanager

- slicedimage/_tile.py
- tests/io/v0_0_0/test_write.py
Tiles can be read multiple times, but each time it decodes from the backend.  The application is responsbile for caching it if necessary.
Depends on #71 
Test plan: make -j test
> Provide no caching for the data

- slicedimage/_tile.py
- tests/io/v0_0_0/test_missing_shape.py
If the tile_shape is not provided by the json file, we should infer it from the actual data.  This is a suboptimal data path since it requires a decoding step just to get the shape of the tile, so we warn about it.
Previously, this field was set by `_load()`, but that was removed in #72.
Test plan: Generate a tileset document, and then strip the shape data from the tiles.  Then read it back.  The correct tile shapes should be provided, but getting them should trigger a warning.
> Record the tile shape in our data structures if it's not provided.

- slicedimage/_tileset.py
Obtain the tile shape through:
1. read the tile's declared shape without forcing a read & decode of the tile data.
2. read the tileset's default tile shape.
3. read the tile's shape through a read & decode.
Print the range of tile sizes, if it's a variety of values, or a scalar if all the tiles are the same size.
This is a continuation of #57.
Test plan:
```
<starfish.Experiment (FOVs=1)>
{
fov_001: <starfish.FieldOfView>
Primary Image: <starfish.ImageStack (r: 4, c: 4, z: 1, y: 1044, x: 1390)>
Auxiliary Images:
nuclei: <slicedimage.TileSet (r: 1, c: 1, x: 1044, y: 1390)>
dots: <slicedimage.TileSet (r: 1, c: 1, x: 1044, y: 1390)>
}
```
> Add __repr__ to TileSet

- slicedimage/io.py
Currently, the tile format is correctly set when we write a TileSet.  If we writte a Collection, the tile format needs to be propagated to the lower level write calls.
Test plan:
```
[tt (.venv)]:~/microscopy/starfish:master> python examples/get_iss_breast_data.py /Users/ttung/Downloads/starfish_data/mignardi_breast_1/raw/ ../starfish-formatted-data/breast/ 1
[tt (.venv)]:~/microscopy/starfish:master> file ../starfish-formatted-data/breast/primary_image-fov_000-Z0-H0-C0.tiff
../starfish-formatted-data/breast/primary_image-fov_000-Z0-H0-C0.tiff: TIFF image data, little-endian, direntries=14, height=1044, bps=16, compression=none, PhotometricIntepretation=BlackIsZero, description={"shape": [1044, 1390]}, width=1390
```
> Propagate tile_format for multi-level images

- slicedimage/_typeformatting.py
- tests/test_tile_coordinates.py
The format states:
```
"xc": {
"type": "array",
"minItems": 1,
"maxItems": 2,
```
suggesting that a coordinate of length one will be accepted. For the
moment, this loosens the `slicedimage` restriction to allow for either
a scalar or an array of size 1 or 2 until the two can be unified.
> Accept coordinate arrays of size 1

- slicedimage/_tileset.py
Coordinates in geometric space are not part of the non-geometric shape, so don't try reading them.
Test plan: repr(..) on the seqfish TileSet.
> Prevent exception in repr(..)

- .travis.yml
It seems to be choking on travis consistently.
> [easy] Drop python 3.4 support.

- README.rst
- tests/io/v0_0_0/test_missing_shape.py
- tests/io/v0_0_0/test_reader.py
- tests/io/v0_0_0/test_write.py
It should be y, x.
Adjusted the tests to catch future misinterpretations of the ordering of tile_shape.
This is part of the resolution for https://github.com/spacetx/starfish/issues/528.
> Fix ordering of tile pixel dimensions.

- tests/io/v0_0_0/test_missing_shape.py
- tests/io/v0_0_0/test_reader.py
- tests/io/v0_0_0/test_write.py
- tests/io/v1_0_0/test_missing_shape.py
- tests/io/v1_0_0/test_reader.py
- tests/io/v1_0_0/test_write.py
This is the follow on of https://github.com/spacetx/slicedimage/pull/81#discussion_r264361845
> reformat existing usages of 'x' and 'y'

- requirements.txt
- slicedimage/io.py
URLs are POSIX path formatted, even on Windows.
> Use POSIX paths on Windows.

- setup.py
- slicedimage/io.py
Refactor slicedimage write path to use pathlib.
This is a functional no-op.  Bumps the version because the API has been modified.
Depends on #85
> Refactor slicedimage write path to use pathlib.

- slicedimage/io.py
- tests/io/v1_0_0/test_write.py
Rather than writing the basename of a referenced file, calculate the relative path from the current file and record that.  Adds a test to verify that such behavior works.
This is the last piece of slicedimage work necessary for https://github.com/spacetx/starfish/issues/1116
Depends on #86
> Permit writing of images to hierarchical on-disk representations.

- tests/io_/v0_1_0/test_http_backend.py
This is facilitate the testing of a retriable HTTP request.  We need to monkeypatch the status codes that trigger a HTTP retry.
1. Remove the unittest class construct.
2. Make the http server a fixture.
> Refactor http backend test as a pytest

- slicedimage/_formats.py
Currently, skimage methods only support file-like objects or a string path.  Since pathlib is so very convenient and easy to deal with, this adds support to pathlib objects to the reader and writers.
Test plan: used in https://github.com/spacetx/starfish/pull/1421
> Add support for pathlib objects in skimage read/write methods

- slicedimage/_compat.py
- slicedimage/io.py
Previously, we just extracted the path component and used that as the base path for the DiskCache backend.  However, on Windows, we need to convert the path separators to forward slashes.  We do this by parsing the URL into a posix path, and then creating a local system path from the path components.
Test plan: would be great if this was tested on Windows....
> Fix conversion of file:// URLs to local paths.

- setup.py
- slicedimage/__init__.py
- slicedimage/backends/_disk.py
- slicedimage/io/__init__.py
- slicedimage/io/_base.py
- slicedimage/io/_v0_0_0.py
- slicedimage/io/_v0_1_0.py
- tests/io_/v0_0_0/test_missing_shape.py
- tests/io_/v0_0_0/test_reader.py
- tests/io_/v0_0_0/test_write.py
- tests/io_/v0_1_0/test_missing_shape.py
- tests/io_/v0_1_0/test_reader.py
- tests/io_/v0_1_0/test_write.py
Previously, the read path for slicedimage operated with URLs.  This allowed us to have manifests on local disk that referred to network resources for tiles.  This PR will use URLs as the destination for manifest files and tile data.
This PR also changes the way users can control the behavior of writing.  Previously, we allowed for two callbacks: one allowed callers to designate where a sub-manifest is located on disk, and the other allowed callers to open a file for writing tile data.  This turns out not to capture all the use cases for how we might want to control writing, so this PR creates WriterContract.  It has three callbacks: one to designate where a sub-manifest is located in URL-space, another to designate where a tile is located in URL space, and one to write tile data to a URL. …
> Switch write path to transact in URLs

- setup.py
- slicedimage/backends/_s3.py
- slicedimage/io/_base.py
Constructing a S3 handle takes up memory and time.  We retrieve the backend whenever we initialize a tile, but we want to delay the expensive work until the data is requested.
The perf issue is sufficiently bad that we want to do a release, so bumping to 4.0.1.
Test plan: Able to quickly load an experiment where all the tiles are located in th ecloud.
> Delay S3 resource construction until object requested

- slicedimage/url/resolve.py
When extracting the path component from urllib.parse.urlparse, the path always starts with '/'.  When tokenizing the url into its components, it becomes '/', 'c:', 'windows', 'system32'.  Unfortunately, when combined into a WindowsPath, it becomes 'c:windows/system32', which honestly makes no sense to me.
The approach here is to strip the prefix '/', and when we do that, WindowsPath can parse the posix path correctly.
Thanks to @dany-fu for reporting this.
Test plan: loaded up a very empty experiment.json on a Windows VM.
> Fix Windows path resolution

- tests/io_/v0_0_0/test_caching_backend.py
- tests/io_/v0_0_0/test_http_backend.py
- tests/io_/v0_1_0/test_caching_backend.py
We have a mechanism for tracking multiple context managers for unit test setup and teardown.  For unwinding them context managers, we should unwind them in the reverse order they are created.
On POSIX systems, this does not matter, as we can hold file handles to files that are deleted.  However, on Windows, the ordering is critical as one cannot delete files that are still held open.
In the case where we create a temporary directory, and then spin up a http server to listen to requests at that directory, we need to kill the process _before_ we clean up the temporary directory.
Test plan: works on windows
> [easy] Reverse context unwind

- tests/io_/v0_0_0/test_caching_backend.py
- tests/io_/v0_1_0/test_caching_backend.py
It's not possible on Windows, with standard filesystem calls, to open the same file twice.  Reentrant tests on the disk backend requires that behavior, so this disables the test on Windows.
Test plan: Windows!
Part of spacetx/starfish#1296
> [easy] disable reentrant tests

- tests/io_/v0_0_0/test_caching_backend.py
- tests/io_/v0_0_0/test_http_backend.py
- tests/io_/v0_1_0/test_caching_backend.py
- tests/io_/v0_1_0/test_http_backend.py
Windows does not like binding to 0.0.0.0 (all interfaces on POSIX systems).  Bind to 127.0.0.1, which works.
Test plan: pass on Windows.
> [easy] Change 0.0.0.0 to 127.0.0.1

- tests/io_/v0_0_0/test_caching_backend.py
- tests/io_/v0_1_0/test_caching_backend.py
- tests/utils/__init__.py
- tests/utils/contextualcachingbackend.py
In our caching tests, we create a temporary directory, and then initialize a cache in that temporary directory.  The issue is that the cache handle holds an open file handle, and on Windows, the cleanup of the temporary directory fails if the cache handle still exists.
The fix is to add a context manager to remove the cache handle.
Test plan: works on windows
Depends on #115 
> Clean up our usage of DiskCache

- tests/io_/v0_0_0/test_caching_backend.py
- tests/io_/v0_0_0/test_http_backend.py
- tests/io_/v0_1_0/test_caching_backend.py
- tests/io_/v0_1_0/test_http_backend.py
We removed python 2.x support in #102, so this code should and can be simplified.
Test plan: `make -j test`
> Simplify HTTP connection code

- tests/io_/test_resolve_url.py
- tests/io_/v0_0_0/test_missing_shape.py
- tests/io_/v0_0_0/test_reader.py
- tests/io_/v0_0_0/test_write.py
- tests/io_/v0_1_0/test_http_backend.py
- tests/io_/v0_1_0/test_missing_shape.py
- tests/io_/v0_1_0/test_reader.py
- tests/io_/v0_1_0/test_write.py
Use Pathlib's `as_uri()` method, which is cross-platform.
Test plan: `make test`
> Eliminate string construction of file:// urls.

- tests/io_/test_resolve_url.py
- tests/io_/v0_0_0/test_caching_backend.py
- tests/io_/v0_0_0/test_disk_backend.py
- tests/io_/v0_0_0/test_http_backend.py
- tests/io_/v0_0_0/test_missing_shape.py
- tests/io_/v0_0_0/test_write.py
- tests/io_/v0_1_0/test_caching_backend.py
- tests/io_/v0_1_0/test_disk_backend.py
- tests/io_/v0_1_0/test_http_backend.py
- tests/io_/v0_1_0/test_missing_shape.py
- tests/io_/v0_1_0/test_write.py
It's not possible, using python stdlib, to open a file in Windows for write and read simultaneously.  A common idiom in the test code is to set up a temporary file using `with tempfile.NamedTemporaryFile()`, write some content to it, and then switch to the test code, and then cleaning up the temp file when the `with` statement goes out of scope.
This is incompatible with Windows, so we instead just create the temporary file, write out the necessary contents, and then close it (and not delete it).  We rely on the temporary directory cleanup to ensure that the files eventually get cleaned up.
On the */test_disk_backend.py, we were not using a temporary directory, so we add that.
Test plan: works on windows
Depends on #117 
> Close files before using them in tests

- slicedimage/io/_base.py
`as_uri()` is a better API than urlunparse, which doesn't handle Windows backslashes.
Part of https://github.com/spacetx/starfish/issues/1493
> Fix path composition in old write_to_path API

- slicedimage/backends/_caching.py
- slicedimage/backends/_disk.py
- slicedimage/backends/_http.py
- slicedimage/backends/_s3.py
- slicedimage/io/_v0_0_0.py
- slicedimage/io/_v0_1_0.py
1. File handles are not picklable, even if they are closed.  Therefore, `self.handle` should be cleared after `__exit__` is called.
2. Callables with bound variables not defined locally cannot be pickled.  The same purpose can be achieved by a class that has a `__call__` method.
Test plan: Successfully pickled an ImageStack in starfish.
> Ensure that Tiles are picklable

- requirements.txt
- slicedimage/_formats.py
- tests/io_/v0_0_0/test_reader.py
- tests/io_/v0_0_0/test_write.py
- tests/io_/v0_1_0/test_reader.py
- tests/io_/v0_1_0/test_write.py
This PR adds PNG reader/writer support via `imageio`.
Testing:
> Add png reader/writer

- requirements-dev.txt
- tests/io_/v0_0_0/test_reader.py
- tests/io_/v0_1_0/test_reader.py
- tests/io_/v0_1_0/test_write.py
1. Remove the tests for file formats in test_reader.  test_write already verifies the write-then-read path.
2. Add test that identifies the tiles using python-magic (backed by libmagic) and asserts they are of the file type we requested.
Test plan: make -j test
Depends on https://github.com/spacetx/slicedimage/pull/127 and https://github.com/kevinyamauchi/slicedimage/pull/1
> Better tests for file formats

- .travis.yml
- tests/io_/v0_1_0/test_write.py
python-magic doesn't work for win32.  python-magic-win64 appears to be the substitute for Windows.
Test plan: travis
> Fix windows build

- slicedimage/_formats.py
- tests/test_nd_tiff.py
Switching tiff to using imageio broke 3D tiff operations, as imageio handles 3D images through `volread` and `volwrite`.  This PR updates tiff handling to use those methods when appropriate.
Test plan: add tests to read and write 2d and 3d tiffs.
> Fix 3D TIFF read/write

- .travis.yml
- requirements-dev.txt
- slicedimage/io/_v0_0_0.py
- slicedimage/io/_v0_1_0.py
doc_version should be of instance `version.Version`
Couple additional build-related issues:
1. hackery for Windows builds no longer necessary!
2. running into https://github.com/ahupp/python-magic/issues/213, so pinning python-magic to an earlier version.
> [easy] fix typing errors in `can_parse`
